# Site settings
title: Raúl Gómez blog
email: raulgombru@gmail.com
description: "Computer vision, deep learning and image processing stuff by Raúl Gómez Bruballa, PhD in computer vision."
baseurl: ""
url: "http://gombru.github.io"
twitter_username: gombru
github_username:  gombru
linkedin_username:  raulgomezbruballa

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
