# Site settings
title: Raúl Gombru blog
email: raulgombru@gmail.com
description: "Computer vision, deep learning and image processing stuff."
baseurl: ""
url: "http://gombru.github.io"
twitter_username: gombru
github_username:  gombru

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
