# Site settings
title: Raúl Gombru
email: raulgombru@gmail.com
description: "Raúl Gómez Bruballa personal website."
baseurl: ""
url: "http://gombru.github.io"
twitter_username: gombru
github_username:  gombru

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
